# This file controls the AWS CodeBuild

version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - mvn clean install spring-boot:repackage
  post_build:
    commands:
      - echo "Entered the post-build phase"
      - mv target/alpha-SNAPSHOT.war ROOT.war
artifacts:
  files:
    - ROOT.war